# Generated by Django 3.0.1 on 2019-12-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication',
            field=models.IntegerField(default=0),
        ),
    ]
