# Generated by Django 3.0.1 on 2019-12-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_communication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanLiness',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(default=5),
        ),
    ]
